// ============================================================================
//  BÀM BAR — MENU DATA
//  ---------------------------------------------------------------------------
//  This is the ONLY file you need to touch to edit the menu.
//  • Prices are in Malaysian Ringgit (RM) and already include 5% service tax.
//  • Each category has a `key` (used by the tabs), a `label`, an optional
//    `note`, and a list of `items`.
//  • An item is: { name, desc?, price }  — `price` is a plain string.
//    For multi-tier prices (e.g. beer kegs) write them slash-separated,
//    e.g. "175 / 90 / 19", and label the tiers in `desc` / the category `note`.
//  Add, remove, or reorder freely — the site rebuilds the tabs automatically.
//  Prices below are transcribed from the official BÀM menu.
// ============================================================================

export const menu = [
  {
    key: 'cocktails',
    label: 'Cocktails',
    note: 'Bottled cocktails — RM30 each',
    items: [
      { name: 'BÀM Signature', desc: 'Vodka · Cointreau · sangria', price: '30' },
      { name: 'Deep Blue Sea', desc: 'Gin · lychee · blue curaçao', price: '30' },
      { name: '6AM', desc: 'Tequila · mango · orange juice', price: '30' },
      { name: '3 Masam', desc: 'Tuak · langkau · fruit syrup', price: '30' },
      { name: 'Cool Your Ass Down', desc: 'White rum · calamansi · peach', price: '30' },
      { name: 'Vitagen Booster', desc: 'Soju · yogurt', price: '30' },
    ],
  },
  {
    key: 'mocktails',
    label: 'Mocktails',
    note: 'Alcohol-free',
    items: [
      { name: 'BÀM Lemonade', price: '20' },
      { name: 'Blue Pea Mango Lime Soda', price: '15' },
      { name: 'Blue Pea Orange Soda', price: '15' },
      { name: 'Elderflower Peach Cooler', price: '18' },
      { name: 'Virgin Mojito', price: '15' },
      { name: 'Strawberry Fizz', price: '15' },
      { name: 'Honey Lemon Soda', price: '15' },
      { name: 'Sunset Sipper', price: '10' },
      { name: 'Apple Peach Tea', price: '15' },
    ],
  },
  {
    key: 'beverages',
    label: 'Beverages',
    note: 'Hot & cold',
    items: [
      { name: 'Ice Lemon Tea', price: '6' },
      { name: 'Ice Honey Lemon', price: '6' },
      { name: 'Hot Lemon Tea', price: '5' },
      { name: 'Hot Honey Lemon', price: '5' },
      { name: 'Ribena Sprite Lychee', price: '15' },
      { name: 'Ribena Sprite', price: '10' },
      { name: 'Milo Dinosaur', price: '15' },
      { name: 'Cincau Rose Milk', price: '12' },
      { name: 'Strawberry Iced Coffee', price: '15' },
    ],
  },
  {
    key: 'juices',
    label: 'Juices',
    note: 'Freshly pressed',
    items: [
      { name: 'Orange Juice', price: '8' },
      { name: 'Apple Juice', price: '8' },
      { name: 'Pink Guava Juice', price: '8' },
    ],
  },
  {
    key: 'cans',
    label: 'Cans & Bottles',
    note: 'Soft drinks & water',
    items: [
      { name: 'Coke', price: '6' },
      { name: 'Sprite / 7Up', price: '6' },
      { name: '100 Plus', price: '6' },
      { name: 'Green Tea', price: '6' },
      { name: 'Tonic Water', price: '8' },
      { name: 'Energy Drink', price: '8' },
      { name: 'Soda Water', price: '8' },
      { name: 'Ginger Ale', price: '8' },
      { name: 'Mineral Water', price: '5' },
      { name: 'Cold / Warm Water', price: '1' },
    ],
  },
  {
    key: 'beer',
    label: 'Beer',
    note: 'Draught priced by keg (10L / 5L / 1L). Bottled priced by 3 bottles / 1 bottle.',
    items: [
      { name: 'Carlsberg', desc: 'Draught · 10L / 5L / 1L', price: '175 / 90 / 19' },
      { name: "Connor's", desc: 'Draught · 10L / 5L / 1L', price: '175 / 90 / 19' },
      { name: 'Sapporo', desc: 'Draught · 10L / 5L / 1L', price: '180 / 95 / 20' },
      { name: '1664 Blanc', desc: 'Draught · 10L / 5L / 1L', price: '180 / 95 / 20' },
      { name: 'Carlsberg Pilsner', desc: 'Bottled · 3 / 1', price: '90 / 30' },
      { name: 'Carlsberg Smooth', desc: 'Bottled · 3 / 1', price: '90 / 30' },
      { name: 'Somersby Apple Cider', desc: 'Bottled · 3 / 1', price: '50 / 18' },
      { name: '1664 Brut / Blanc', desc: 'Bottled · 3 / 1', price: '50 / 18' },
      { name: 'Soju', desc: 'Random flavour · 4 btls / 1', price: '118 / 30' },
    ],
  },
  {
    key: 'liquor',
    label: 'Liquor',
    note: 'Every bottle comes with 4 canned mixers (coke, sprite, soda, tonic, green tea or ginger ale)',
    items: [
      { name: 'Glenlivet Founder', price: '518' },
      { name: 'Glenlivet 12 Year', price: '558' },
      { name: 'Jameson Black Barrel', price: '508' },
      { name: 'Chivas XY 15 Years', price: '558' },
      { name: 'Glenfiddich 12 Year', price: '508' },
      { name: 'Glenfiddich 15 Year', price: '558' },
      { name: 'Baileys', price: '220' },
      { name: 'Monkey Shoulder', price: '458' },
      { name: "Jack Daniel's", price: '348' },
      { name: 'Chivas Regal 12', price: '298' },
      { name: 'Singleton Luscious Nectar', price: '498' },
      { name: "Hendrick's", price: '468' },
      { name: 'Bombay Sapphire', price: '378' },
      { name: 'Jägermeister', price: '338' },
      { name: 'Tequila Camino', price: '298' },
      { name: 'Absolut Vodka Original', price: '338' },
      { name: 'Absolut Vodka Lemon', price: '338' },
      { name: 'Hennessy VSOP', price: '598' },
      { name: 'Martell VSOP', price: '598' },
      { name: 'Roku Gin', price: '398' },
      { name: 'Jameson Irish Whisky', price: '438' },
    ],
  },
  {
    key: 'shots',
    label: 'Shots',
    note: 'Go big with the BÀM Hundred',
    items: [
      { name: 'Tequila', price: '60' },
      { name: 'Jägerbomb', price: '60' },
      { name: 'BÀM Boom', price: '70' },
      { name: 'B51', desc: 'Baileys + kahlua + rum', price: '70' },
      { name: 'B52', desc: 'Baileys + kahlua + triple sec', price: '70' },
      { name: 'B53', desc: 'Baileys + kahlua + tequila', price: '70' },
      { name: 'BMW', desc: 'Baileys + malibu + whiskey', price: '70' },
      { name: 'BJOB', desc: 'Kahlua + baileys + whipped cream', price: '70' },
      { name: 'Quick F', desc: 'Kahlua + midori + baileys', price: '70' },
      { name: 'E.T. Alien', desc: 'Midori + baileys + vodka', price: '70' },
      { name: 'Blue Kamikaze', desc: 'Vodka + blue curaçao', price: '62' },
      { name: 'BÀM Hundred — 100 shots', desc: 'The whole squad', price: '999' },
      { name: 'BÀM Fifty — 50 shots', price: '599' },
    ],
  },
  {
    key: 'wine',
    label: 'Wine & Bubbly',
    note: 'Reds, whites, tuak & Champagne',
    items: [
      { name: 'Tamaron 2014', price: '207' },
      { name: 'Tamaron 2016', price: '186' },
      { name: 'The Family', price: '155' },
      { name: 'Gran Castillo', price: '155' },
      { name: 'Riunite Lambrusco', price: '147' },
      { name: 'I Feudali', price: '144' },
      { name: 'Bin 555', price: '135' },
      { name: 'Bin 999', price: '135' },
      { name: 'Bin 888', price: '135' },
      { name: 'Moët', price: '550' },
      { name: 'Marguerite Classic', price: '480' },
      { name: 'Mei Jian', price: '360' },
      { name: 'La Mancha', price: '165' },
      { name: 'Endu Tuak Roselle', price: '155' },
      { name: 'Endu Tuak Classic', price: '155' },
      { name: "Vin's Art", price: '145' },
      { name: 'Christina', price: '134' },
      { name: 'Rodafuerte', price: '134' },
    ],
  },
  {
    key: 'food',
    label: 'Food',
    note: 'Bar bites & mains',
    items: [
      { name: 'Chicken Katsu', desc: 'Burnt cheese & apple curry', price: '16' },
      { name: 'Crispy Japanese Ebi Prawn', desc: 'Pickle ginger & wasabi mayo', price: '16' },
      { name: 'Charred Edamame', desc: 'Sea salt', price: '10' },
      { name: 'Shishamo Fish', desc: 'Pickle ginger', price: '13' },
      { name: 'Fried Nian Gao', price: '12' },
      { name: 'Fried Banana Popiah', price: '12' },
      { name: 'Scallion Fried Pork Stripes', desc: 'Chinese BBQ powder', price: '20' },
      { name: 'Fish Skin with Ebi Mayo', price: '12' },
      { name: 'Crispy Prawn Popiah', desc: 'Ebiko mayo', price: '20' },
      { name: 'Crispy Parmesan Fries', price: '15' },
      { name: 'Crispy Mantao', desc: 'Salted egg chicken fillet', price: '15' },
      { name: 'Fried Garlic Pork Ribs', price: '28' },
      { name: 'Loaded Nachos', price: '25' },
      { name: 'Spanish Sausage', desc: 'Pickle & mustard', price: '22' },
      { name: 'Crispy Bacon Stripes', desc: 'Grilled pineapple', price: '18' },
      { name: 'Signature Chicken Wings', price: '22' },
      { name: 'Crispy Enoki Mushroom', desc: 'Salted egg sauce & pickle mayo', price: '12' },
      { name: 'Stir Fry Anchovies & Pineapple', price: '8' },
      { name: 'Grilled Saba Fish', price: '13' },
      { name: 'Japanese Chicken Dumpling', price: '15' },
    ],
  },
]

// A one-off headliner shown separately (birthday moment).
export const special = {
  name: 'Flaming Waterfall',
  desc: 'The birthday drink. Lights out, everyone watching.',
  price: '70',
}
